### ISSUE TITLE
Think about convenient way to show fractional time

### ISSUE THREAD

**Issue by ChShersh** [serokell/o-clock#61]
Currently fractional time is shown as normalized fractional, like this:

```haskell
ghci> show $ Time @Second (180 % 7)
"180/7s"
```

This might be not so convenient... (see usage example in #60)

I think something like this would be more useful:

```haskell
ghci> show $ Time @Second (180 % 7)
"25+5/7s"
```

Not sure about format. Exactly this looks a little bit ugly to me... But maybe it's okay.

**Comment by adituv** [comment]
If you choose to use the mixed fraction representation, I've written an implementation of show for that: https://gist.github.com/adituv/5486a7f6aebbf3945b604d6304cc1366

You're welcome to use it directly or as a base for your own modifications.

(I didn't submit it as a patch or anything because it seemed like you were still deciding what to do about the show instance)

**Comment by ChShersh** [comment]
@adituv Sorry for long answer 🙏 Your PR for this issue is welcome! So you can contribute if you're interested :) I looked at your code and it looks good. But note, that `Time` can't be negative so your solution can be slightly simplified here:

* https://gist.github.com/adituv/5486a7f6aebbf3945b604d6304cc1366#file-ratio-hs-L27

**Comment by ChShersh** [comment]
@adituv Are you planning to work on this?

**Comment by adituv** [comment]
Sorry for not following up!  Sure I'll work on this, but would like to clarify one thing before I submit it: are we using this for Show/Read instances, or just for `seriesF` etc?
